checkpoint_frequency: null
data_dir: data/
dataset: WikiText2
epochs: 4
learning_rate: 0.025
model_dir: weights/cbow_WikiText2-CL2
model_name: cbow
optimizer: Adam
shuffle: true
train_batch_size: 96
train_steps: null
val_batch_size: 96
val_steps: null
